name: Terraform

on: [push]

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff -recursive

      - name: Terraform Init
        id: init
        run: terraform -chdir=./webapp init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=./webapp validate

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=./webapp plan

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=./webapp apply -auto-approve
